export const TEAMGEST_STORAGE_PREFIX = 'teamgest'
export const SERVICES_CREATED_KEY = `${TEAMGEST_STORAGE_PREFIX}:services:created`
export const LEGACY_SERVICES_CREATED_KEY = 'costaflow.services.local'
export const SERVICES_OVERRIDES_KEY = `${TEAMGEST_STORAGE_PREFIX}:services:overrides`
export const SERVICES_ARCHIVED_KEY = `${TEAMGEST_STORAGE_PREFIX}:services:archived`
export const WORKERS_CREATED_KEY = `${TEAMGEST_STORAGE_PREFIX}:workers:created`
export const WORKERS_OVERRIDES_KEY = `${TEAMGEST_STORAGE_PREFIX}:workers:overrides`
export const WORKERS_ARCHIVED_KEY = `${TEAMGEST_STORAGE_PREFIX}:workers:archived`
export const CLIENTS_CREATED_KEY = `${TEAMGEST_STORAGE_PREFIX}:clients:created`
export const CLIENTS_OVERRIDES_KEY = `${TEAMGEST_STORAGE_PREFIX}:clients:overrides`
export const CLIENTS_ARCHIVED_KEY = `${TEAMGEST_STORAGE_PREFIX}:clients:archived`
export const PROPERTIES_CREATED_KEY = `${TEAMGEST_STORAGE_PREFIX}:properties:created`
export const PROPERTIES_OVERRIDES_KEY = `${TEAMGEST_STORAGE_PREFIX}:properties:overrides`
export const PROPERTIES_ARCHIVED_KEY = `${TEAMGEST_STORAGE_PREFIX}:properties:archived`
export const PAYROLL_MONTHS_KEY = `${TEAMGEST_STORAGE_PREFIX}:payroll:months`
export const PAYROLL_AUDIT_KEY = `${TEAMGEST_STORAGE_PREFIX}:payroll:audit`
export const APP_AUDIT_KEY = `${TEAMGEST_STORAGE_PREFIX}:app:audit`
export const STORAGE_METADATA_KEY = `${TEAMGEST_STORAGE_PREFIX}:storage:metadata`
export const SETTINGS_KEY = `${TEAMGEST_STORAGE_PREFIX}:settings`
export const BACKUP_HISTORY_KEY = `${TEAMGEST_STORAGE_PREFIX}:backup:history`

export const TEAMGEST_EXPECTED_STORAGE_KEYS = [
  SERVICES_CREATED_KEY,
  SERVICES_OVERRIDES_KEY,
  SERVICES_ARCHIVED_KEY,
  WORKERS_CREATED_KEY,
  WORKERS_OVERRIDES_KEY,
  WORKERS_ARCHIVED_KEY,
  CLIENTS_CREATED_KEY,
  CLIENTS_OVERRIDES_KEY,
  CLIENTS_ARCHIVED_KEY,
  PROPERTIES_CREATED_KEY,
  PROPERTIES_OVERRIDES_KEY,
  PROPERTIES_ARCHIVED_KEY,
  PAYROLL_MONTHS_KEY,
  PAYROLL_AUDIT_KEY,
  APP_AUDIT_KEY,
  STORAGE_METADATA_KEY,
  SETTINGS_KEY,
  BACKUP_HISTORY_KEY,
] as const
