export const dataMappingPlan = {
  workers: {
    source: 'Worker',
    target: 'workers',
    fields: {
      id: 'id',
      name: 'name',
      role: 'role',
      defaultHourlyRate: 'default_hourly_rate',
      status: 'status',
      notes: 'notes',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  },
  clients: {
    source: 'Client',
    target: 'clients',
    fields: {
      id: 'id',
      name: 'name',
      phone: 'phone',
      email: 'email',
      billingName: 'billing_name',
      billingTaxId: 'billing_tax_id',
      billingAddress: 'billing_address',
      status: 'status',
      notes: 'notes',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  },
  properties: {
    source: 'Property',
    target: 'properties',
    fields: {
      id: 'id',
      clientId: 'client_id',
      name: 'name',
      propertyType: 'property_type',
      address: 'address',
      city: 'city',
      status: 'status',
      notes: 'notes',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  },
  serviceJobs: {
    source: 'ServiceJob',
    target: 'service_jobs',
    fields: {
      id: 'id',
      clientId: 'client_id',
      propertyId: 'property_id',
      serviceType: 'service_type',
      date: 'date',
      startTime: 'start_time',
      endTime: 'end_time',
      status: 'status',
      notes: 'notes',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
    childTable: 'service_assignments',
  },
  serviceAssignments: {
    source: 'ServiceAssignment',
    target: 'service_assignments',
    fields: {
      id: 'id',
      serviceJobId: 'service_job_id',
      workerId: 'worker_id',
      hoursWorked: 'hours_worked',
      hourlyRate: 'hourly_rate',
      extraAmount: 'extra_amount',
      deductions: 'deductions',
      confirmed: 'confirmed',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  },
  payrollMonths: {
    source: 'PayrollMonthState',
    target: 'payroll_months',
    fields: {
      month: 'month_key',
      status: 'status',
      lockedAt: 'locked_at',
      lockedSnapshot: 'locked_snapshot_json',
      updatedAt: 'updated_at',
    },
    childTable: 'payroll_worker_statuses',
  },
  appAuditEntries: {
    source: 'AppAuditEntry',
    target: 'app_audit_entries',
    fields: {
      id: 'id',
      action: 'action',
      entityType: 'entity_type',
      entityId: 'entity_id',
      message: 'message',
      metadata: 'metadata_json',
      createdAt: 'created_at',
    },
  },
  enumMapping: {
    entityStatus: ['active', 'inactive', 'archived'],
    serviceStatus: ['draft', 'scheduled', 'in_progress', 'completed', 'reviewed', 'closed', 'cancelled'],
    payrollStatus: ['pending', 'reviewed', 'paid', 'locked'],
  },
  notes: [
    'Keep timestamps as ISO strings during export, then cast to timestamptz on import.',
    'Preserve local ids during migration to avoid breaking cross-entity references.',
    'Archived entities should map to deleted_at or archived status rather than hard delete.',
    'Local backup payloads should transform through validated import steps before reaching real tables.',
  ],
} as const
