export const supabaseSchemaPlan = {
  tables: {
    users: ['id', 'email', 'role', 'created_at', 'updated_at'],
    profiles: ['id', 'user_id', 'display_name', 'phone', 'created_at', 'updated_at'],
    workers: ['id', 'name', 'role', 'default_hourly_rate', 'status', 'notes', 'created_at', 'updated_at', 'deleted_at'],
    clients: ['id', 'name', 'phone', 'email', 'billing_name', 'billing_tax_id', 'billing_address', 'status', 'notes', 'created_at', 'updated_at', 'deleted_at'],
    properties: ['id', 'client_id', 'name', 'property_type', 'address', 'city', 'status', 'notes', 'created_at', 'updated_at', 'deleted_at'],
    service_jobs: ['id', 'client_id', 'property_id', 'service_type', 'date', 'start_time', 'end_time', 'status', 'notes', 'created_at', 'updated_at', 'deleted_at'],
    service_assignments: ['id', 'service_job_id', 'worker_id', 'hours_worked', 'hourly_rate', 'extra_amount', 'deductions', 'confirmed', 'created_at', 'updated_at'],
    payroll_months: ['id', 'month_key', 'status', 'locked_at', 'locked_snapshot_json', 'created_at', 'updated_at'],
    payroll_worker_statuses: ['id', 'payroll_month_id', 'worker_id', 'status', 'created_at', 'updated_at'],
    payroll_audit_entries: ['id', 'payroll_month_id', 'action', 'message', 'metadata_json', 'created_at'],
    app_audit_entries: ['id', 'action', 'entity_type', 'entity_id', 'message', 'metadata_json', 'created_at'],
    app_settings: ['id', 'scope', 'settings_json', 'created_at', 'updated_at'],
    storage_backups: ['id', 'exported_at', 'source_mode', 'summary_json', 'created_at'],
  },
  relationships: [
    'profiles.user_id -> users.id',
    'properties.client_id -> clients.id',
    'service_jobs.client_id -> clients.id',
    'service_jobs.property_id -> properties.id',
    'service_assignments.service_job_id -> service_jobs.id',
    'service_assignments.worker_id -> workers.id',
    'payroll_worker_statuses.payroll_month_id -> payroll_months.id',
    'payroll_worker_statuses.worker_id -> workers.id',
    'payroll_audit_entries.payroll_month_id -> payroll_months.id',
  ],
  indexes: [
    'workers(status)',
    'clients(status)',
    'properties(client_id, status)',
    'service_jobs(date, status)',
    'service_jobs(client_id, date)',
    'service_jobs(property_id, date)',
    'service_assignments(worker_id, confirmed)',
    'payroll_months(month_key)',
    'payroll_worker_statuses(payroll_month_id, worker_id)',
    'app_audit_entries(action, created_at desc)',
  ],
  rlsNotes: [
    'Workers should only read their own assigned services once auth exists.',
    'Managers and admins need write access to service_jobs and service_assignments.',
    'Payroll tables should be restricted to managers, admins, and accountant-like roles.',
    'Audit tables should be append-only for application roles.',
  ],
  migrationNotes: [
    'Map current local ids directly where possible to simplify local-to-real migration.',
    'Preserve status enums rather than translating to opaque integers.',
    'Add deleted_at for archive-ready soft delete strategy.',
    'Store lock snapshots as JSON initially, then normalize later only if reporting needs it.',
  ],
} as const
